spring.application.name=managementsystem

spring.datasource.url=jdbc:mysql://localhost:3306/english_center
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

#Show generated SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.invoice.generation-cron=0 0 1 1 * *

app.invoice.pro-rate-first-month = true
